version: "3.3"
services:
  api_hack:
    container_name: api_hack
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
    ports:
      - 4444:4444
    expose:
      - 4444
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackTest
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - hackTest:/var/lib/postgresql/data
    ports:
      - 5416:5432
    expose:
      - 5416
    restart: always
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
       - 80:80
    restart: unless-stopped
volumes:
  hackTest:
  pgadmin: